--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-28-2020   
--------------------------------------------------------
REM INSERTING into BOARD
SET DEFINE OFF;
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('F','123','자유게시판',to_date('20/07/24','RR/MM/DD'),null,1,'Y','Y','N','N','Y',3,1048576,'B','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('SNF','123','분실물/습득물',to_date('20/07/24','RR/MM/DD'),null,2,'Y','Y','N','N','Y',3,1048576,'B','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('M','123','벼룩시장',to_date('20/07/24','RR/MM/DD'),null,3,'Y','Y','N','N','Y',3,1048576,'B','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('R','123','하숙자취방정보',to_date('20/07/24','RR/MM/DD'),null,4,'Y','Y','N','N','Y',3,1048576,'B','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('P','123','포털공지',to_date('20/07/27','RR/MM/DD'),null,1,'Y','N','N','N','N',0,0,'N','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('H','123','홈페이지공지',to_date('20/07/27','RR/MM/DD'),null,2,'Y','N','N','N','N',0,0,'N','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('W','123','서식자료실',to_date('20/07/27','RR/MM/DD'),null,1,'Y','N','N','N','Y',5,10485760,'P','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('PG','123','프로그램자료실',to_date('20/07/27','RR/MM/DD'),null,2,'Y','N','N','N','Y',5,10485760,'P','STAFF');
Insert into BOARD (BD_CODE,OFFICIAL_NO,BD_NAME,REG_DATE,EDIT_DATE,BD_ORDER,USAGE,IS_REPLY,IS_COMMENT,IS_PRIVATE,IS_UPLOAD,MAX_UPFILE,MAX_FILESIZE,CATEGORY_CODE,AUTH_CODE) values ('NON','123','미사용게시판',to_date('20/07/24','RR/MM/DD'),null,1,'N','Y','N','N','Y',3,1048576,'B','STAFF');
